// File generated by Antigravity (configured for CarelineMed).
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8lYX4PpdH4pGyeJgS9EBnW1Z68-ZaR68',
    appId: '1:720619866387:android:f8e6b3d7cb5ad4e8bf32e6',
    messagingSenderId: '720619866387',
    projectId: 'meetmedicine-digontom',
    storageBucket: 'meetmedicine-digontom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEewvx1riXm7js_mmJ4HN2NghtItT1Jf8',
    appId: '1:720619866387:ios:dd9346338c9d0675bf32e6',
    messagingSenderId: '720619866387',
    projectId: 'meetmedicine-digontom',
    storageBucket: 'meetmedicine-digontom.firebasestorage.app',
    iosBundleId: 'com.digontom.carelinemed',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUB5TRHOFiWuiBw0bmbZiJTKEJuisXLow',
    appId: '1:720619866387:web:8ecd45d540cfecf2bf32e6',
    messagingSenderId: '720619866387',
    projectId: 'meetmedicine-digontom',
    authDomain: 'meetmedicine-digontom.firebaseapp.com',
    storageBucket: 'meetmedicine-digontom.firebasestorage.app',
    measurementId: 'G-0CYRG0WMNV',
  );

}